language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository -y ppa:archivematica/externals
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo apt-get update
  - sudo apt-get install libfreetype6-dev libfontconfig1-dev libpango1.0-dev librsvg2-dev liblcms2-dev libzip-dev libcdr-dev libicu-dev libcppunit-dev
  - sudo apt-get install cmake libtinyxml-dev liblcms2-dev libyaml-cpp-dev libboost-dev
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf
  - wget https://github.com/imageworks/OpenColorIO/archive/v1.0.9.tar.gz -O /tmp/ocio-1.0.9.tar.gz
  - tar zxf /tmp/ocio-1.0.9.tar.gz > /dev/null 2>&1
  - cd OpenColorIO-1.0.9
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DOCIO_BUILD_JNIGLUE=OFF -DOCIO_BUILD_NUKE=OFF -DOCIO_BUILD_SHARED=ON -DOCIO_BUILD_STATIC=OFF -DOCIO_STATIC_JNIGLUE=OFF -DOCIO_BUILD_TRUELIGHT=OFF -DUSE_EXTERNAL_LCMS=ON -DUSE_EXTERNAL_TINYXML=ON -DUSE_EXTERNAL_YAML=ON -DOCIO_BUILD_APPS=OFF -DOCIO_USE_BOOST_PTR=ON -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_PYGLUE=OFF
  - make $MAKEFLAGSPARALLEL && sudo make install
  - cd ../..

script:
  - git submodule update -i --recursive
  - FIX_TRAVIS=1 DEBUG=1 bash deploy.sh
