sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install -y cmake libfreetype6-dev libfontconfig1-dev libpango1.0-dev librsvg2-dev liblcms2-dev libzip-dev libcdr-dev libicu-dev libcppunit-dev libopencolorio-dev librevenge-dev libboost-all-dev gtk-doc-tools libharfbuzz-dev libselinux1-dev libpoppler-glib-dev libcurl4-openssl-dev
  - sudo rm -rf /usr/include/libcdr* /usr/lib*/*cdr* /usr/lib*/pkgconfig/*cdr*
  - git clone https://github.com/LibreOffice/libcdr
  - cd libcdr
  - sh autogen.sh
  - ./configure --prefix=/usr
  - make -j2
  - sudo make install
  - cd ..
  - git clone https://github.com/ImageMagick/ImageMagick
  - cd ImageMagick
  - git checkout tags/7.0.3-1
  - ./configure --prefix=/usr --disable-docs --disable-deprecated --with-magick-plus-plus=yes --with-quantum-depth=32 --without-dps --without-djvu --without-fftw --without-fpx --without-gslib --without-gvc --without-jbig --without-jpeg --with-lcms --without-openjp2 --without-lqr --without-lzma --without-openexr --without-pango --with-png --without-rsvg --without-tiff --without-webp --without-xml --with-zlib --without-bzlib --enable-static --enable-shared --enable-hdri --with-freetype --with-fontconfig --without-x --without-modules --without-wmf
  - make -j2
  - sudo make install
  - cd ..
  - wget https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-0.9.42.tar.bz2
  - tar xf harfbuzz-0.9.42.tar.bz2
  - cd harfbuzz-0.9.42
  - ./configure --prefix=/usr/local
  - make -j2
  - sudo make install
  - cd ..
  - wget http://ftp.gnome.org/pub/GNOME/sources/pango/1.38/pango-1.38.1.tar.xz
  - tar xf pango-1.38.1.tar.xz
  - cd pango-1.38.1
  - env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig LD_LIBRARY_PATH=/usr/local/lib ./configure --prefix=/usr/local
  - make -j2
  - sudo make install
  - cd ..

script:
  - git submodule update -i --recursive
  - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig LD_LIBRARY_PATH=/usr/local/lib make IM=7 CONFIG=debug
  - make -C ArenaCL
#  - mkdir build && cd build
#  - cmake .. && make
