language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install libfreetype6-dev libfontconfig1-dev

script:
  - git submodule update -i
  - MAGICK_LEGACY=1 MAGICK_MOD=1 PACKAGE=Text VERSION=3.2 bash deploy.sh
